project:
  type: website
  output-dir: ../docs/_site # Render the website to a nested directory

website:
  title: "Academic-CV Template"
  search:
    location: navbar
    type: overlay
  navbar:
    tools:
      - icon: github
        href:  https://github.com/orehren/acvt
    left:
      - href: index.qmd
        text: Home
      - href: installation.qmd
        text: Installation
      - href: tutorial.qmd
        text: How to get started
      - href: data_integration.qmd
        text: Data Integration
      - href: shortcodes.qmd
        text: Shortcodes
      - href: styling.qmd
        text: Styling
      - href: structure.qmd
        text: Structure
      - href: update_template.qmd
        text: Template Update
      - href: yaml_reference.qmd
        text: YAML Reference
      - href: acknowledgements.qmd
        text: Acknowledgements

format:
  html:
    theme:
      light: [cosmo, template-light.scss]
      dark: [cosmo, template-dark.scss]
    toc: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    keep-md: true # Keep the markdown files
    number-sections: false

execute:
  eval: false # Don't execute code chunks for the website
