name: Render and Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'doc_src/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Documentation Website
        run: |
          quarto render doc_src
          cp doc_src/*.md docs/

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Docs: Rebuild and deploy documentation website"
          branch: main
          file_pattern: docs/**
          repository: .
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
